#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhiemvu_WebAPI.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNV")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAuthentication(Authentication instance);
    partial void UpdateAuthentication(Authentication instance);
    partial void DeleteAuthentication(Authentication instance);
    partial void InsertDBDM0163(DBDM0163 instance);
    partial void UpdateDBDM0163(DBDM0163 instance);
    partial void DeleteDBDM0163(DBDM0163 instance);
    partial void InsertDBDM0160(DBDM0160 instance);
    partial void UpdateDBDM0160(DBDM0160 instance);
    partial void DeleteDBDM0160(DBDM0160 instance);
    partial void InsertDBDM0161(DBDM0161 instance);
    partial void UpdateDBDM0161(DBDM0161 instance);
    partial void DeleteDBDM0161(DBDM0161 instance);
    partial void InsertDBDM0162(DBDM0162 instance);
    partial void UpdateDBDM0162(DBDM0162 instance);
    partial void DeleteDBDM0162(DBDM0162 instance);
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLNVConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Authentication> Authentications
		{
			get
			{
				return this.GetTable<Authentication>();
			}
		}
		
		public System.Data.Linq.Table<DBDM0163> DBDM0163s
		{
			get
			{
				return this.GetTable<DBDM0163>();
			}
		}
		
		public System.Data.Linq.Table<DBDM0160> DBDM0160s
		{
			get
			{
				return this.GetTable<DBDM0160>();
			}
		}
		
		public System.Data.Linq.Table<DBDM0161> DBDM0161s
		{
			get
			{
				return this.GetTable<DBDM0161>();
			}
		}
		
		public System.Data.Linq.Table<DBDM0162> DBDM0162s
		{
			get
			{
				return this.GetTable<DBDM0162>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Authentications")]
	public partial class Authentication : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Username;
		
		private string _Password;
		
		private string _Description;
		
		private string _ListIPs;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnListIPsChanging(string value);
    partial void OnListIPsChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Authentication()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListIPs", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ListIPs
		{
			get
			{
				return this._ListIPs;
			}
			set
			{
				if ((this._ListIPs != value))
				{
					this.OnListIPsChanging(value);
					this.SendPropertyChanging();
					this._ListIPs = value;
					this.SendPropertyChanged("ListIPs");
					this.OnListIPsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBDM0163")]
	public partial class DBDM0163 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DM016301;
		
		private System.Guid _DM016302;
		
		private string _DM016303;
		
		private string _DM016304;
		
		private char _DM016305;
		
		private System.Guid _DM016306;
		
		private System.DateTime _DM016307;
		
		private System.Guid _DM016308;
		
		private System.DateTime _DM016309;
		
		private bool _DM016310;
		
		private EntityRef<DBDM0160> _DBDM0160;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDM016301Changing(System.Guid value);
    partial void OnDM016301Changed();
    partial void OnDM016302Changing(System.Guid value);
    partial void OnDM016302Changed();
    partial void OnDM016303Changing(string value);
    partial void OnDM016303Changed();
    partial void OnDM016304Changing(string value);
    partial void OnDM016304Changed();
    partial void OnDM016305Changing(char value);
    partial void OnDM016305Changed();
    partial void OnDM016306Changing(System.Guid value);
    partial void OnDM016306Changed();
    partial void OnDM016307Changing(System.DateTime value);
    partial void OnDM016307Changed();
    partial void OnDM016308Changing(System.Guid value);
    partial void OnDM016308Changed();
    partial void OnDM016309Changing(System.DateTime value);
    partial void OnDM016309Changed();
    partial void OnDM016310Changing(bool value);
    partial void OnDM016310Changed();
    #endregion
		
		public DBDM0163()
		{
			this._DBDM0160 = default(EntityRef<DBDM0160>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016301", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DM016301
		{
			get
			{
				return this._DM016301;
			}
			set
			{
				if ((this._DM016301 != value))
				{
					this.OnDM016301Changing(value);
					this.SendPropertyChanging();
					this._DM016301 = value;
					this.SendPropertyChanged("DM016301");
					this.OnDM016301Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016302", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016302
		{
			get
			{
				return this._DM016302;
			}
			set
			{
				if ((this._DM016302 != value))
				{
					if (this._DBDM0160.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDM016302Changing(value);
					this.SendPropertyChanging();
					this._DM016302 = value;
					this.SendPropertyChanged("DM016302");
					this.OnDM016302Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016303", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DM016303
		{
			get
			{
				return this._DM016303;
			}
			set
			{
				if ((this._DM016303 != value))
				{
					this.OnDM016303Changing(value);
					this.SendPropertyChanging();
					this._DM016303 = value;
					this.SendPropertyChanged("DM016303");
					this.OnDM016303Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016304", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DM016304
		{
			get
			{
				return this._DM016304;
			}
			set
			{
				if ((this._DM016304 != value))
				{
					this.OnDM016304Changing(value);
					this.SendPropertyChanging();
					this._DM016304 = value;
					this.SendPropertyChanged("DM016304");
					this.OnDM016304Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016305", DbType="NChar(1) NOT NULL")]
		public char DM016305
		{
			get
			{
				return this._DM016305;
			}
			set
			{
				if ((this._DM016305 != value))
				{
					this.OnDM016305Changing(value);
					this.SendPropertyChanging();
					this._DM016305 = value;
					this.SendPropertyChanged("DM016305");
					this.OnDM016305Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016306", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016306
		{
			get
			{
				return this._DM016306;
			}
			set
			{
				if ((this._DM016306 != value))
				{
					this.OnDM016306Changing(value);
					this.SendPropertyChanging();
					this._DM016306 = value;
					this.SendPropertyChanged("DM016306");
					this.OnDM016306Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016307", DbType="DateTime NOT NULL")]
		public System.DateTime DM016307
		{
			get
			{
				return this._DM016307;
			}
			set
			{
				if ((this._DM016307 != value))
				{
					this.OnDM016307Changing(value);
					this.SendPropertyChanging();
					this._DM016307 = value;
					this.SendPropertyChanged("DM016307");
					this.OnDM016307Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016308", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016308
		{
			get
			{
				return this._DM016308;
			}
			set
			{
				if ((this._DM016308 != value))
				{
					this.OnDM016308Changing(value);
					this.SendPropertyChanging();
					this._DM016308 = value;
					this.SendPropertyChanged("DM016308");
					this.OnDM016308Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016309", DbType="DateTime NOT NULL")]
		public System.DateTime DM016309
		{
			get
			{
				return this._DM016309;
			}
			set
			{
				if ((this._DM016309 != value))
				{
					this.OnDM016309Changing(value);
					this.SendPropertyChanging();
					this._DM016309 = value;
					this.SendPropertyChanged("DM016309");
					this.OnDM016309Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016310", DbType="Bit NOT NULL")]
		public bool DM016310
		{
			get
			{
				return this._DM016310;
			}
			set
			{
				if ((this._DM016310 != value))
				{
					this.OnDM016310Changing(value);
					this.SendPropertyChanging();
					this._DM016310 = value;
					this.SendPropertyChanged("DM016310");
					this.OnDM016310Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBDM0160_DBDM0163", Storage="_DBDM0160", ThisKey="DM016302", OtherKey="DM016001", IsForeignKey=true)]
		public DBDM0160 DBDM0160
		{
			get
			{
				return this._DBDM0160.Entity;
			}
			set
			{
				DBDM0160 previousValue = this._DBDM0160.Entity;
				if (((previousValue != value) 
							|| (this._DBDM0160.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBDM0160.Entity = null;
						previousValue.DBDM0163s.Remove(this);
					}
					this._DBDM0160.Entity = value;
					if ((value != null))
					{
						value.DBDM0163s.Add(this);
						this._DM016302 = value.DM016001;
					}
					else
					{
						this._DM016302 = default(System.Guid);
					}
					this.SendPropertyChanged("DBDM0160");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBDM0160")]
	public partial class DBDM0160 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DM016001;
		
		private System.Guid _DM016002;
		
		private string _DM016003;
		
		private string _DM016004;
		
		private char _DM016005;
		
		private System.Guid _DM016006;
		
		private System.DateTime _DM016007;
		
		private System.Guid _DM016008;
		
		private System.DateTime _DM016009;
		
		private char _DM016010;
		
		private bool _DM016011;
		
		private EntitySet<DBDM0161> _DBDM0161s;
		
		private EntitySet<DBDM0163> _DBDM0163s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDM016001Changing(System.Guid value);
    partial void OnDM016001Changed();
    partial void OnDM016002Changing(System.Guid value);
    partial void OnDM016002Changed();
    partial void OnDM016003Changing(string value);
    partial void OnDM016003Changed();
    partial void OnDM016004Changing(string value);
    partial void OnDM016004Changed();
    partial void OnDM016005Changing(char value);
    partial void OnDM016005Changed();
    partial void OnDM016006Changing(System.Guid value);
    partial void OnDM016006Changed();
    partial void OnDM016007Changing(System.DateTime value);
    partial void OnDM016007Changed();
    partial void OnDM016008Changing(System.Guid value);
    partial void OnDM016008Changed();
    partial void OnDM016009Changing(System.DateTime value);
    partial void OnDM016009Changed();
    partial void OnDM016010Changing(char value);
    partial void OnDM016010Changed();
    partial void OnDM016011Changing(bool value);
    partial void OnDM016011Changed();
    #endregion
		
		public DBDM0160()
		{
			this._DBDM0161s = new EntitySet<DBDM0161>(new Action<DBDM0161>(this.attach_DBDM0161s), new Action<DBDM0161>(this.detach_DBDM0161s));
			this._DBDM0163s = new EntitySet<DBDM0163>(new Action<DBDM0163>(this.attach_DBDM0163s), new Action<DBDM0163>(this.detach_DBDM0163s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016001", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DM016001
		{
			get
			{
				return this._DM016001;
			}
			set
			{
				if ((this._DM016001 != value))
				{
					this.OnDM016001Changing(value);
					this.SendPropertyChanging();
					this._DM016001 = value;
					this.SendPropertyChanged("DM016001");
					this.OnDM016001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016002", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016002
		{
			get
			{
				return this._DM016002;
			}
			set
			{
				if ((this._DM016002 != value))
				{
					this.OnDM016002Changing(value);
					this.SendPropertyChanging();
					this._DM016002 = value;
					this.SendPropertyChanged("DM016002");
					this.OnDM016002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016003", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DM016003
		{
			get
			{
				return this._DM016003;
			}
			set
			{
				if ((this._DM016003 != value))
				{
					this.OnDM016003Changing(value);
					this.SendPropertyChanging();
					this._DM016003 = value;
					this.SendPropertyChanged("DM016003");
					this.OnDM016003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016004", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DM016004
		{
			get
			{
				return this._DM016004;
			}
			set
			{
				if ((this._DM016004 != value))
				{
					this.OnDM016004Changing(value);
					this.SendPropertyChanging();
					this._DM016004 = value;
					this.SendPropertyChanged("DM016004");
					this.OnDM016004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016005", DbType="NChar(1) NOT NULL")]
		public char DM016005
		{
			get
			{
				return this._DM016005;
			}
			set
			{
				if ((this._DM016005 != value))
				{
					this.OnDM016005Changing(value);
					this.SendPropertyChanging();
					this._DM016005 = value;
					this.SendPropertyChanged("DM016005");
					this.OnDM016005Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016006", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016006
		{
			get
			{
				return this._DM016006;
			}
			set
			{
				if ((this._DM016006 != value))
				{
					this.OnDM016006Changing(value);
					this.SendPropertyChanging();
					this._DM016006 = value;
					this.SendPropertyChanged("DM016006");
					this.OnDM016006Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016007", DbType="DateTime NOT NULL")]
		public System.DateTime DM016007
		{
			get
			{
				return this._DM016007;
			}
			set
			{
				if ((this._DM016007 != value))
				{
					this.OnDM016007Changing(value);
					this.SendPropertyChanging();
					this._DM016007 = value;
					this.SendPropertyChanged("DM016007");
					this.OnDM016007Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016008", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016008
		{
			get
			{
				return this._DM016008;
			}
			set
			{
				if ((this._DM016008 != value))
				{
					this.OnDM016008Changing(value);
					this.SendPropertyChanging();
					this._DM016008 = value;
					this.SendPropertyChanged("DM016008");
					this.OnDM016008Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016009", DbType="DateTime NOT NULL")]
		public System.DateTime DM016009
		{
			get
			{
				return this._DM016009;
			}
			set
			{
				if ((this._DM016009 != value))
				{
					this.OnDM016009Changing(value);
					this.SendPropertyChanging();
					this._DM016009 = value;
					this.SendPropertyChanged("DM016009");
					this.OnDM016009Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016010", DbType="NChar(1) NOT NULL")]
		public char DM016010
		{
			get
			{
				return this._DM016010;
			}
			set
			{
				if ((this._DM016010 != value))
				{
					this.OnDM016010Changing(value);
					this.SendPropertyChanging();
					this._DM016010 = value;
					this.SendPropertyChanged("DM016010");
					this.OnDM016010Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016011", DbType="Bit NOT NULL")]
		public bool DM016011
		{
			get
			{
				return this._DM016011;
			}
			set
			{
				if ((this._DM016011 != value))
				{
					this.OnDM016011Changing(value);
					this.SendPropertyChanging();
					this._DM016011 = value;
					this.SendPropertyChanged("DM016011");
					this.OnDM016011Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBDM0160_DBDM0161", Storage="_DBDM0161s", ThisKey="DM016001", OtherKey="DM016102")]
		public EntitySet<DBDM0161> DBDM0161s
		{
			get
			{
				return this._DBDM0161s;
			}
			set
			{
				this._DBDM0161s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBDM0160_DBDM0163", Storage="_DBDM0163s", ThisKey="DM016001", OtherKey="DM016302")]
		public EntitySet<DBDM0163> DBDM0163s
		{
			get
			{
				return this._DBDM0163s;
			}
			set
			{
				this._DBDM0163s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DBDM0161s(DBDM0161 entity)
		{
			this.SendPropertyChanging();
			entity.DBDM0160 = this;
		}
		
		private void detach_DBDM0161s(DBDM0161 entity)
		{
			this.SendPropertyChanging();
			entity.DBDM0160 = null;
		}
		
		private void attach_DBDM0163s(DBDM0163 entity)
		{
			this.SendPropertyChanging();
			entity.DBDM0160 = this;
		}
		
		private void detach_DBDM0163s(DBDM0163 entity)
		{
			this.SendPropertyChanging();
			entity.DBDM0160 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBDM0161")]
	public partial class DBDM0161 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DM016101;
		
		private System.Guid _DM016102;
		
		private string _DM016103;
		
		private string _DM016104;
		
		private char _DM016105;
		
		private System.Guid _DM016106;
		
		private System.DateTime _DM016107;
		
		private System.Guid _DM016108;
		
		private System.DateTime _DM016109;
		
		private string _DM016110;
		
		private bool _DM016111;
		
		private EntityRef<DBDM0160> _DBDM0160;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDM016101Changing(System.Guid value);
    partial void OnDM016101Changed();
    partial void OnDM016102Changing(System.Guid value);
    partial void OnDM016102Changed();
    partial void OnDM016103Changing(string value);
    partial void OnDM016103Changed();
    partial void OnDM016104Changing(string value);
    partial void OnDM016104Changed();
    partial void OnDM016105Changing(char value);
    partial void OnDM016105Changed();
    partial void OnDM016106Changing(System.Guid value);
    partial void OnDM016106Changed();
    partial void OnDM016107Changing(System.DateTime value);
    partial void OnDM016107Changed();
    partial void OnDM016108Changing(System.Guid value);
    partial void OnDM016108Changed();
    partial void OnDM016109Changing(System.DateTime value);
    partial void OnDM016109Changed();
    partial void OnDM016110Changing(string value);
    partial void OnDM016110Changed();
    partial void OnDM016111Changing(bool value);
    partial void OnDM016111Changed();
    #endregion
		
		public DBDM0161()
		{
			this._DBDM0160 = default(EntityRef<DBDM0160>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016101", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DM016101
		{
			get
			{
				return this._DM016101;
			}
			set
			{
				if ((this._DM016101 != value))
				{
					this.OnDM016101Changing(value);
					this.SendPropertyChanging();
					this._DM016101 = value;
					this.SendPropertyChanged("DM016101");
					this.OnDM016101Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016102", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016102
		{
			get
			{
				return this._DM016102;
			}
			set
			{
				if ((this._DM016102 != value))
				{
					if (this._DBDM0160.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDM016102Changing(value);
					this.SendPropertyChanging();
					this._DM016102 = value;
					this.SendPropertyChanged("DM016102");
					this.OnDM016102Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016103", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DM016103
		{
			get
			{
				return this._DM016103;
			}
			set
			{
				if ((this._DM016103 != value))
				{
					this.OnDM016103Changing(value);
					this.SendPropertyChanging();
					this._DM016103 = value;
					this.SendPropertyChanged("DM016103");
					this.OnDM016103Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016104", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DM016104
		{
			get
			{
				return this._DM016104;
			}
			set
			{
				if ((this._DM016104 != value))
				{
					this.OnDM016104Changing(value);
					this.SendPropertyChanging();
					this._DM016104 = value;
					this.SendPropertyChanged("DM016104");
					this.OnDM016104Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016105", DbType="NChar(1) NOT NULL")]
		public char DM016105
		{
			get
			{
				return this._DM016105;
			}
			set
			{
				if ((this._DM016105 != value))
				{
					this.OnDM016105Changing(value);
					this.SendPropertyChanging();
					this._DM016105 = value;
					this.SendPropertyChanged("DM016105");
					this.OnDM016105Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016106", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016106
		{
			get
			{
				return this._DM016106;
			}
			set
			{
				if ((this._DM016106 != value))
				{
					this.OnDM016106Changing(value);
					this.SendPropertyChanging();
					this._DM016106 = value;
					this.SendPropertyChanged("DM016106");
					this.OnDM016106Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016107", DbType="DateTime NOT NULL")]
		public System.DateTime DM016107
		{
			get
			{
				return this._DM016107;
			}
			set
			{
				if ((this._DM016107 != value))
				{
					this.OnDM016107Changing(value);
					this.SendPropertyChanging();
					this._DM016107 = value;
					this.SendPropertyChanged("DM016107");
					this.OnDM016107Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016108", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016108
		{
			get
			{
				return this._DM016108;
			}
			set
			{
				if ((this._DM016108 != value))
				{
					this.OnDM016108Changing(value);
					this.SendPropertyChanging();
					this._DM016108 = value;
					this.SendPropertyChanged("DM016108");
					this.OnDM016108Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016109", DbType="DateTime NOT NULL")]
		public System.DateTime DM016109
		{
			get
			{
				return this._DM016109;
			}
			set
			{
				if ((this._DM016109 != value))
				{
					this.OnDM016109Changing(value);
					this.SendPropertyChanging();
					this._DM016109 = value;
					this.SendPropertyChanged("DM016109");
					this.OnDM016109Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016110", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DM016110
		{
			get
			{
				return this._DM016110;
			}
			set
			{
				if ((this._DM016110 != value))
				{
					this.OnDM016110Changing(value);
					this.SendPropertyChanging();
					this._DM016110 = value;
					this.SendPropertyChanged("DM016110");
					this.OnDM016110Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016111", DbType="Bit NOT NULL")]
		public bool DM016111
		{
			get
			{
				return this._DM016111;
			}
			set
			{
				if ((this._DM016111 != value))
				{
					this.OnDM016111Changing(value);
					this.SendPropertyChanging();
					this._DM016111 = value;
					this.SendPropertyChanged("DM016111");
					this.OnDM016111Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DBDM0160_DBDM0161", Storage="_DBDM0160", ThisKey="DM016102", OtherKey="DM016001", IsForeignKey=true)]
		public DBDM0160 DBDM0160
		{
			get
			{
				return this._DBDM0160.Entity;
			}
			set
			{
				DBDM0160 previousValue = this._DBDM0160.Entity;
				if (((previousValue != value) 
							|| (this._DBDM0160.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DBDM0160.Entity = null;
						previousValue.DBDM0161s.Remove(this);
					}
					this._DBDM0160.Entity = value;
					if ((value != null))
					{
						value.DBDM0161s.Add(this);
						this._DM016102 = value.DM016001;
					}
					else
					{
						this._DM016102 = default(System.Guid);
					}
					this.SendPropertyChanged("DBDM0160");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DBDM0162")]
	public partial class DBDM0162 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DM016201;
		
		private System.Guid _DM016202;
		
		private System.Guid _DM016203;
		
		private string _DM016204;
		
		private string _DM016205;
		
		private string _DM016206;
		
		private string _DM016207;
		
		private System.Nullable<int> _DM016208;
		
		private string _DM016209;
		
		private string _DM016210;
		
		private string _DM016211;
		
		private string _DM016212;
		
		private string _DM016213;
		
		private int _DM016214;
		
		private char _DM016215;
		
		private System.Guid _DM016216;
		
		private System.Guid _DM016217;
		
		private System.DateTime _DM016218;
		
		private System.Guid _DM016219;
		
		private System.DateTime _DM016220;
		
		private bool _DM016221;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDM016201Changing(System.Guid value);
    partial void OnDM016201Changed();
    partial void OnDM016202Changing(System.Guid value);
    partial void OnDM016202Changed();
    partial void OnDM016203Changing(System.Guid value);
    partial void OnDM016203Changed();
    partial void OnDM016204Changing(string value);
    partial void OnDM016204Changed();
    partial void OnDM016205Changing(string value);
    partial void OnDM016205Changed();
    partial void OnDM016206Changing(string value);
    partial void OnDM016206Changed();
    partial void OnDM016207Changing(string value);
    partial void OnDM016207Changed();
    partial void OnDM016208Changing(System.Nullable<int> value);
    partial void OnDM016208Changed();
    partial void OnDM016209Changing(string value);
    partial void OnDM016209Changed();
    partial void OnDM016210Changing(string value);
    partial void OnDM016210Changed();
    partial void OnDM016211Changing(string value);
    partial void OnDM016211Changed();
    partial void OnDM016212Changing(string value);
    partial void OnDM016212Changed();
    partial void OnDM016213Changing(string value);
    partial void OnDM016213Changed();
    partial void OnDM016214Changing(int value);
    partial void OnDM016214Changed();
    partial void OnDM016215Changing(char value);
    partial void OnDM016215Changed();
    partial void OnDM016216Changing(System.Guid value);
    partial void OnDM016216Changed();
    partial void OnDM016217Changing(System.Guid value);
    partial void OnDM016217Changed();
    partial void OnDM016218Changing(System.DateTime value);
    partial void OnDM016218Changed();
    partial void OnDM016219Changing(System.Guid value);
    partial void OnDM016219Changed();
    partial void OnDM016220Changing(System.DateTime value);
    partial void OnDM016220Changed();
    partial void OnDM016221Changing(bool value);
    partial void OnDM016221Changed();
    #endregion
		
		public DBDM0162()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016201", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DM016201
		{
			get
			{
				return this._DM016201;
			}
			set
			{
				if ((this._DM016201 != value))
				{
					this.OnDM016201Changing(value);
					this.SendPropertyChanging();
					this._DM016201 = value;
					this.SendPropertyChanged("DM016201");
					this.OnDM016201Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016202", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016202
		{
			get
			{
				return this._DM016202;
			}
			set
			{
				if ((this._DM016202 != value))
				{
					this.OnDM016202Changing(value);
					this.SendPropertyChanging();
					this._DM016202 = value;
					this.SendPropertyChanged("DM016202");
					this.OnDM016202Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016203", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016203
		{
			get
			{
				return this._DM016203;
			}
			set
			{
				if ((this._DM016203 != value))
				{
					this.OnDM016203Changing(value);
					this.SendPropertyChanging();
					this._DM016203 = value;
					this.SendPropertyChanged("DM016203");
					this.OnDM016203Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016204", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DM016204
		{
			get
			{
				return this._DM016204;
			}
			set
			{
				if ((this._DM016204 != value))
				{
					this.OnDM016204Changing(value);
					this.SendPropertyChanging();
					this._DM016204 = value;
					this.SendPropertyChanged("DM016204");
					this.OnDM016204Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016205", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DM016205
		{
			get
			{
				return this._DM016205;
			}
			set
			{
				if ((this._DM016205 != value))
				{
					this.OnDM016205Changing(value);
					this.SendPropertyChanging();
					this._DM016205 = value;
					this.SendPropertyChanged("DM016205");
					this.OnDM016205Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016206", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DM016206
		{
			get
			{
				return this._DM016206;
			}
			set
			{
				if ((this._DM016206 != value))
				{
					this.OnDM016206Changing(value);
					this.SendPropertyChanging();
					this._DM016206 = value;
					this.SendPropertyChanged("DM016206");
					this.OnDM016206Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016207", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string DM016207
		{
			get
			{
				return this._DM016207;
			}
			set
			{
				if ((this._DM016207 != value))
				{
					this.OnDM016207Changing(value);
					this.SendPropertyChanging();
					this._DM016207 = value;
					this.SendPropertyChanged("DM016207");
					this.OnDM016207Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016208", DbType="Int")]
		public System.Nullable<int> DM016208
		{
			get
			{
				return this._DM016208;
			}
			set
			{
				if ((this._DM016208 != value))
				{
					this.OnDM016208Changing(value);
					this.SendPropertyChanging();
					this._DM016208 = value;
					this.SendPropertyChanged("DM016208");
					this.OnDM016208Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016209", DbType="NVarChar(2)")]
		public string DM016209
		{
			get
			{
				return this._DM016209;
			}
			set
			{
				if ((this._DM016209 != value))
				{
					this.OnDM016209Changing(value);
					this.SendPropertyChanging();
					this._DM016209 = value;
					this.SendPropertyChanged("DM016209");
					this.OnDM016209Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016210", DbType="NVarChar(50)")]
		public string DM016210
		{
			get
			{
				return this._DM016210;
			}
			set
			{
				if ((this._DM016210 != value))
				{
					this.OnDM016210Changing(value);
					this.SendPropertyChanging();
					this._DM016210 = value;
					this.SendPropertyChanged("DM016210");
					this.OnDM016210Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016211", DbType="NVarChar(100)")]
		public string DM016211
		{
			get
			{
				return this._DM016211;
			}
			set
			{
				if ((this._DM016211 != value))
				{
					this.OnDM016211Changing(value);
					this.SendPropertyChanging();
					this._DM016211 = value;
					this.SendPropertyChanged("DM016211");
					this.OnDM016211Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016212", DbType="NVarChar(100)")]
		public string DM016212
		{
			get
			{
				return this._DM016212;
			}
			set
			{
				if ((this._DM016212 != value))
				{
					this.OnDM016212Changing(value);
					this.SendPropertyChanging();
					this._DM016212 = value;
					this.SendPropertyChanged("DM016212");
					this.OnDM016212Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016213", DbType="NVarChar(100)")]
		public string DM016213
		{
			get
			{
				return this._DM016213;
			}
			set
			{
				if ((this._DM016213 != value))
				{
					this.OnDM016213Changing(value);
					this.SendPropertyChanging();
					this._DM016213 = value;
					this.SendPropertyChanged("DM016213");
					this.OnDM016213Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016214", DbType="Int NOT NULL")]
		public int DM016214
		{
			get
			{
				return this._DM016214;
			}
			set
			{
				if ((this._DM016214 != value))
				{
					this.OnDM016214Changing(value);
					this.SendPropertyChanging();
					this._DM016214 = value;
					this.SendPropertyChanged("DM016214");
					this.OnDM016214Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016215", DbType="Char(1) NOT NULL")]
		public char DM016215
		{
			get
			{
				return this._DM016215;
			}
			set
			{
				if ((this._DM016215 != value))
				{
					this.OnDM016215Changing(value);
					this.SendPropertyChanging();
					this._DM016215 = value;
					this.SendPropertyChanged("DM016215");
					this.OnDM016215Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016216", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016216
		{
			get
			{
				return this._DM016216;
			}
			set
			{
				if ((this._DM016216 != value))
				{
					this.OnDM016216Changing(value);
					this.SendPropertyChanging();
					this._DM016216 = value;
					this.SendPropertyChanged("DM016216");
					this.OnDM016216Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016217", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016217
		{
			get
			{
				return this._DM016217;
			}
			set
			{
				if ((this._DM016217 != value))
				{
					this.OnDM016217Changing(value);
					this.SendPropertyChanging();
					this._DM016217 = value;
					this.SendPropertyChanged("DM016217");
					this.OnDM016217Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016218", DbType="DateTime NOT NULL")]
		public System.DateTime DM016218
		{
			get
			{
				return this._DM016218;
			}
			set
			{
				if ((this._DM016218 != value))
				{
					this.OnDM016218Changing(value);
					this.SendPropertyChanging();
					this._DM016218 = value;
					this.SendPropertyChanged("DM016218");
					this.OnDM016218Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016219", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DM016219
		{
			get
			{
				return this._DM016219;
			}
			set
			{
				if ((this._DM016219 != value))
				{
					this.OnDM016219Changing(value);
					this.SendPropertyChanging();
					this._DM016219 = value;
					this.SendPropertyChanged("DM016219");
					this.OnDM016219Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016220", DbType="DateTime NOT NULL")]
		public System.DateTime DM016220
		{
			get
			{
				return this._DM016220;
			}
			set
			{
				if ((this._DM016220 != value))
				{
					this.OnDM016220Changing(value);
					this.SendPropertyChanging();
					this._DM016220 = value;
					this.SendPropertyChanged("DM016220");
					this.OnDM016220Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM016221", DbType="Bit NOT NULL")]
		public bool DM016221
		{
			get
			{
				return this._DM016221;
			}
			set
			{
				if ((this._DM016221 != value))
				{
					this.OnDM016221Changing(value);
					this.SendPropertyChanging();
					this._DM016221 = value;
					this.SendPropertyChanged("DM016221");
					this.OnDM016221Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
