<?xml version="1.0" encoding="utf-8"?><Database Name="QLNV" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=QLNV;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLNVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DBDM0160" Member="DBDM0160s">
    <Type Name="DBDM0160">
      <Column Name="DM016001" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016002" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016003" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DM016004" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM016005" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM016006" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016007" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016008" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016009" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016010" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DM016011" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="false" />
      <Column Name="DM016012" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="false" />
      <Association Name="DBDM0160_DBDM0161" Member="DBDM0161s" ThisKey="DM016001" OtherKey="DM016102" Type="DBDM0161" />
      <Association Name="DBDM0160_DBDM0163" Member="DBDM0163s" ThisKey="DM016001" OtherKey="DM016302" Type="DBDM0163" />
      <Association Name="DBDM0160_DBDM0164" Member="DBDM0164s" ThisKey="DM016001" OtherKey="DM016402" Type="DBDM0164" />
      <Association Name="DBDM0160_DBDM0171" Member="DBDM0171s" ThisKey="DM016001" OtherKey="DM017120" Type="DBDM0171" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0161" Member="DBDM0161s">
    <Type Name="DBDM0161">
      <Column Name="DM016101" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016102" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016103" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DM016104" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM016105" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM016106" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016107" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016108" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016109" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016110" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0161_DBDM0165" Member="DBDM0165s" ThisKey="DM016101" OtherKey="DM016502" Type="DBDM0165" />
      <Association Name="DBDM0161_DBDM0167" Member="DBDM0167s" ThisKey="DM016101" OtherKey="DM016713" Type="DBDM0167" />
      <Association Name="DBDM0161_DBDM0173" Member="DBDM0173s" ThisKey="DM016101" OtherKey="DM017312" Type="DBDM0173" />
      <Association Name="DBDM0161_DBDM0175" Member="DBDM0175s" ThisKey="DM016101" OtherKey="DM017512" Type="DBDM0175" />
      <Association Name="DBDM0160_DBDM0161" Member="DBDM0160" ThisKey="DM016102" OtherKey="DM016001" Type="DBDM0160" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0162" Member="DBDM0162s">
    <Type Name="DBDM0162">
      <Column Name="DM016201" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016204" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DM016205" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM016206" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM016207" Type="System.String" DbType="NChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DM016208" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM016209" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="DM016210" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DM016213" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DM016214" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DM016215" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM016217" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016218" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016219" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016220" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DM016216" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0162_DBDM0164" Member="DBDM0164s" ThisKey="DM016201" OtherKey="DM016403" Type="DBDM0164" />
      <Association Name="DBDM0162_DBDM0165" Member="DBDM0165s" ThisKey="DM016201" OtherKey="DM016503" Type="DBDM0165" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0163" Member="DBDM0163s">
    <Type Name="DBDM0163">
      <Column Name="DM016301" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016302" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016303" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DM016304" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM016305" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM016306" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016307" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016308" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016309" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DM016310" Type="System.String" DbType="NVarChar(500)" CanBeNull="false" />
      <Column Name="DM016311" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0160_DBDM0163" Member="DBDM0160" ThisKey="DM016302" OtherKey="DM016001" Type="DBDM0160" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0164" Member="DBDM0164s">
    <Type Name="DBDM0164">
      <Column Name="DM016401" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016402" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016403" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016404" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016405" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016406" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016407" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0160_DBDM0164" Member="DBDM0160" ThisKey="DM016402" OtherKey="DM016001" Type="DBDM0160" IsForeignKey="true" />
      <Association Name="DBDM0162_DBDM0164" Member="DBDM0162" ThisKey="DM016403" OtherKey="DM016201" Type="DBDM0162" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0165" Member="DBDM0165s">
    <Type Name="DBDM0165">
      <Column Name="DM016501" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016502" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016503" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016504" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016505" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016506" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016507" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0165_DBDM0168" Member="DBDM0168s" ThisKey="DM016501" OtherKey="DM016803" Type="DBDM0168" />
      <Association Name="DBDM0165_DBDM0172" Member="DBDM0172s" ThisKey="DM016501" OtherKey="DM017203" Type="DBDM0172" />
      <Association Name="DBDM0165_DBDM0174" Member="DBDM0174s" ThisKey="DM016501" OtherKey="DM017403" Type="DBDM0174" />
      <Association Name="DBDM0165_DBDM0176" Member="DBDM0176s" ThisKey="DM016501" OtherKey="DM017603" Type="DBDM0176" />
      <Association Name="DBDM0161_DBDM0165" Member="DBDM0161" ThisKey="DM016502" OtherKey="DM016101" Type="DBDM0161" IsForeignKey="true" />
      <Association Name="DBDM0162_DBDM0165" Member="DBDM0162" ThisKey="DM016503" OtherKey="DM016201" Type="DBDM0162" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Authentications" Member="Authentications">
    <Type Name="Authentication">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ListIPs" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0140" Member="DBDM0140s">
    <Type Name="DBDM0140">
      <Column Name="DM014001" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM014002" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DM014003" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DM014004" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM014005" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="DBDM0140_DBDM0202" Member="DBDM0202s" ThisKey="DM014001" OtherKey="DM020205" Type="DBDM0202" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0202" Member="DBDM0202s">
    <Type Name="DBDM0202">
      <Column Name="DM020201" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM020202" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020203" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM020204" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM020205" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020206" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020207" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DM020208" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM020209" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020210" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DM020211" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM020212" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM020213" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020214" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020215" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020216" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM020217" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DM020218" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM020219" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="DBDM0202_DBDM0202" Member="DBDM0202s" ThisKey="DM020201" OtherKey="DM020219" Type="DBDM0202" />
      <Association Name="DBDM0202_DBDM02021" Member="DBDM0202s1" ThisKey="DM020201" OtherKey="DM020219" Type="DBDM0202" />
      <Association Name="DBDM0202_DBDM0167" Member="DBDM0167s" ThisKey="DM020201" OtherKey="DM016705" Type="DBDM0167" />
      <Association Name="DBDM0202_DBDM0171" Member="DBDM0171s" ThisKey="DM020201" OtherKey="DM017104" Type="DBDM0171" />
      <Association Name="DBDM0202_DBDM0173" Member="DBDM0173s" ThisKey="DM020201" OtherKey="DM017304" Type="DBDM0173" />
      <Association Name="DBDM0202_DBDM0175" Member="DBDM0175s" ThisKey="DM020201" OtherKey="DM017504" Type="DBDM0175" />
      <Association Name="DBDM0202_DBDM0202" Member="DBDM02021" ThisKey="DM020219" OtherKey="DM020201" Type="DBDM0202" IsForeignKey="true" />
      <Association Name="DBDM0202_DBDM02021" Member="DBDM02022" ThisKey="DM020219" OtherKey="DM020201" Type="DBDM0202" IsForeignKey="true" />
      <Association Name="DBDM0140_DBDM0202" Member="DBDM0140" ThisKey="DM020205" OtherKey="DM014001" Type="DBDM0140" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0301" Member="DBDM0301s">
    <Type Name="DBDM0301">
      <Column Name="DM030101" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM030102" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030103" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="DM030104" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM030105" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM030106" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DM030107" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DM030108" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DM030109" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM030110" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DM030111" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DM030112" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DM030113" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM030114" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DM030115" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DM030116" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM030117" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="DBDM0301_DBDM0304" Member="DBDM0304s" ThisKey="DM030101" OtherKey="DM030407" Type="DBDM0304" />
      <Association Name="DBDM0107_DBDM0301" Member="DBDM0107" ThisKey="DM030117" OtherKey="DM010701" Type="DBDM0107" IsForeignKey="true" />
      <Association Name="DBDM0107_DBDM03011" Member="DBDM01071" ThisKey="DM030117" OtherKey="DM010701" Type="DBDM0107" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0304" Member="DBDM0304s">
    <Type Name="DBDM0304">
      <Column Name="DM030401" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM030402" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DM030403" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DM030404" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DM030405" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DM030406" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DM030407" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030408" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM030409" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM030410" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030411" Type="System.String" DbType="NVarChar(500)" CanBeNull="false" />
      <Association Name="DBDM0304_DBDM0167" Member="DBDM0167s" ThisKey="DM030401" OtherKey="DM016710" Type="DBDM0167" />
      <Association Name="DBDM0304_DBDM0305" Member="DBDM0305s" ThisKey="DM030401" OtherKey="DM030502" Type="DBDM0305" />
      <Association Name="DBDM0304_DBDM0171" Member="DBDM0171s" ThisKey="DM030401" OtherKey="DM017113" Type="DBDM0171" />
      <Association Name="DBDM0304_DBDM0173" Member="DBDM0173s" ThisKey="DM030401" OtherKey="DM017311" Type="DBDM0173" />
      <Association Name="DBDM0304_DBDM0175" Member="DBDM0175s" ThisKey="DM030401" OtherKey="DM017511" Type="DBDM0175" />
      <Association Name="DBDM0301_DBDM0304" Member="DBDM0301" ThisKey="DM030407" OtherKey="DM030101" Type="DBDM0301" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0167" Member="DBDM0167s">
    <Type Name="DBDM0167">
      <Column Name="DM016701" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016702" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016703" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DM016705" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016706" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM016707" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016708" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM016710" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016711" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DM016713" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016714" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM016715" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM016716" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016717" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016718" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016719" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM016720" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0167_DBDM0169" Member="DBDM0169s" ThisKey="DM016701" OtherKey="DM016902" Type="DBDM0169" />
      <Association Name="DBDM0167_DBDM0168" Member="DBDM0168s" ThisKey="DM016701" OtherKey="DM016802" Type="DBDM0168" />
      <Association Name="DBDM0167_DBDM0170" Member="DBDM0170s" ThisKey="DM016701" OtherKey="DM017002" Type="DBDM0170" />
      <Association Name="DBDM0167_DBDM0171" Member="DBDM0171s" ThisKey="DM016701" OtherKey="DM017109" Type="DBDM0171" />
      <Association Name="DBDM0161_DBDM0167" Member="DBDM0161" ThisKey="DM016713" OtherKey="DM016101" Type="DBDM0161" IsForeignKey="true" />
      <Association Name="DBDM0304_DBDM0167" Member="DBDM0304" ThisKey="DM016710" OtherKey="DM030401" Type="DBDM0304" IsForeignKey="true" />
      <Association Name="DBDM0202_DBDM0167" Member="DBDM0202" ThisKey="DM016705" OtherKey="DM020201" Type="DBDM0202" IsForeignKey="true" />
      <Association Name="DBDM0124_DBDM0167" Member="DBDM0124" ThisKey="DM016720" OtherKey="DM012401" Type="DBDM0124" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0169" Member="DBDM0169s">
    <Type Name="DBDM0169">
      <Column Name="DM016901" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016902" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016903" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016904" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016905" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0167_DBDM0169" Member="DBDM0167" ThisKey="DM016902" OtherKey="DM016701" Type="DBDM0167" IsForeignKey="true" />
      <Association Name="DBDM0124_DBDM0169" Member="DBDM0124" ThisKey="DM016903" OtherKey="DM012401" Type="DBDM0124" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0168" Member="DBDM0168s">
    <Type Name="DBDM0168">
      <Column Name="DM016801" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM016802" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016803" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM016804" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DBDM0167_DBDM0168" Member="DBDM0167" ThisKey="DM016802" OtherKey="DM016701" Type="DBDM0167" IsForeignKey="true" />
      <Association Name="DBDM0165_DBDM0168" Member="DBDM0165" ThisKey="DM016803" OtherKey="DM016501" Type="DBDM0165" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0305" Member="DBDM0305s">
    <Type Name="DBDM0305">
      <Column Name="DM030501" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM030502" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030503" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM030504" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030505" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030506" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM030507" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM030508" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM030509" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030510" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM030511" Type="System.Char" DbType="NChar(1)" CanBeNull="false" />
      <Association Name="DBDM0122_DBDM0305" Member="DBDM0122" ThisKey="DM030504" OtherKey="DM012201" Type="DBDM0122" IsForeignKey="true" />
      <Association Name="DBDM0304_DBDM0305" Member="DBDM0304" ThisKey="DM030502" OtherKey="DM030401" Type="DBDM0304" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0122" Member="DBDM0122s">
    <Type Name="DBDM0122">
      <Column Name="DM012201" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM012202" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM012203" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM012204" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM012205" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM012206" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DBDM0122_DBDM0305" Member="DBDM0305s" ThisKey="DM012201" OtherKey="DM030504" Type="DBDM0305" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0124" Member="DBDM0124s">
    <Type Name="DBDM0124">
      <Column Name="DM012401" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM012402" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM012403" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM012404" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM012405" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="DBDM0124_DBDM0167" Member="DBDM0167s" ThisKey="DM012401" OtherKey="DM016720" Type="DBDM0167" />
      <Association Name="DBDM0124_DBDM0169" Member="DBDM0169s" ThisKey="DM012401" OtherKey="DM016903" Type="DBDM0169" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0170" Member="DBDM0170s">
    <Type Name="DBDM0170">
      <Column Name="DM017001" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017002" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017003" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM017004" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017005" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017006" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017007" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017008" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017009" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017010" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017011" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017012" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0170_DBDM0177" Member="DBDM0177s" ThisKey="DM017001" OtherKey="DM017702" Type="DBDM0177" />
      <Association Name="DBDM0167_DBDM0170" Member="DBDM0167" ThisKey="DM017002" OtherKey="DM016701" Type="DBDM0167" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dbSysMess" Member="dbSysMesses">
    <Type Name="dbSysMess">
      <Column Name="SYS01" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SYS02" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SYS03" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SYS04" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SYS05" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SYS06" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SYS07" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SYS08" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SYS09" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0142" Member="DBDM0142s">
    <Type Name="DBDM0142">
      <Column Name="DM014201" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM014202" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM014203" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="DM014204" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM014205" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM014206" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM014207" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM014208" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM014209" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM014210" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM014211" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0171" Member="DBDM0171s">
    <Type Name="DBDM0171">
      <Column Name="DM017101" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017102" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017103" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DM017104" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017105" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM017106" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017107" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM017108" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017109" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017110" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM017111" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM017112" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017113" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017114" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM017115" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM017116" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DM017117" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM017118" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM017119" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM017120" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DM017121" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DBDM0171_DBDM0172" Member="DBDM0172s" ThisKey="DM017101" OtherKey="DM017202" Type="DBDM0172" />
      <Association Name="DBDM0202_DBDM0171" Member="DBDM0202" ThisKey="DM017104" OtherKey="DM020201" Type="DBDM0202" IsForeignKey="true" />
      <Association Name="DBDM0160_DBDM0171" Member="DBDM0160" ThisKey="DM017120" OtherKey="DM016001" Type="DBDM0160" IsForeignKey="true" />
      <Association Name="DBDM0304_DBDM0171" Member="DBDM0304" ThisKey="DM017113" OtherKey="DM030401" Type="DBDM0304" IsForeignKey="true" />
      <Association Name="DBDM0167_DBDM0171" Member="DBDM0167" ThisKey="DM017109" OtherKey="DM016701" Type="DBDM0167" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0172" Member="DBDM0172s">
    <Type Name="DBDM0172">
      <Column Name="DM017201" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017202" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017203" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017204" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017205" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0171_DBDM0172" Member="DBDM0171" ThisKey="DM017202" OtherKey="DM017101" Type="DBDM0171" IsForeignKey="true" />
      <Association Name="DBDM0165_DBDM0172" Member="DBDM0165" ThisKey="DM017203" OtherKey="DM016501" Type="DBDM0165" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0173" Member="DBDM0173s">
    <Type Name="DBDM0173">
      <Column Name="DM017301" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017302" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017303" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DM017304" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017305" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM017306" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM017307" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM017308" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017309" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM017310" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017311" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017312" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017313" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017314" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017315" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017316" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017317" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017318" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017319" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0173_DBDM0174" Member="DBDM0174s" ThisKey="DM017301" OtherKey="DM017402" Type="DBDM0174" />
      <Association Name="DBDM0202_DBDM0173" Member="DBDM0202" ThisKey="DM017304" OtherKey="DM020201" Type="DBDM0202" IsForeignKey="true" />
      <Association Name="DBDM0107_DBDM0173" Member="DBDM0107" ThisKey="DM017310" OtherKey="DM010701" Type="DBDM0107" IsForeignKey="true" />
      <Association Name="DBDM0304_DBDM0173" Member="DBDM0304" ThisKey="DM017311" OtherKey="DM030401" Type="DBDM0304" IsForeignKey="true" />
      <Association Name="DBDM0161_DBDM0173" Member="DBDM0161" ThisKey="DM017312" OtherKey="DM016101" Type="DBDM0161" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0174" Member="DBDM0174s">
    <Type Name="DBDM0174">
      <Column Name="DM017401" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017402" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017403" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017404" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017405" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0165_DBDM0174" Member="DBDM0165" ThisKey="DM017403" OtherKey="DM016501" Type="DBDM0165" IsForeignKey="true" />
      <Association Name="DBDM0173_DBDM0174" Member="DBDM0173" ThisKey="DM017402" OtherKey="DM017301" Type="DBDM0173" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0107" Member="DBDM0107s">
    <Type Name="DBDM0107">
      <Column Name="DM010701" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM010702" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM010703" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DM010704" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DM010705" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="DM010706" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DBDM0107_DBDM0301" Member="DBDM0301s" ThisKey="DM010701" OtherKey="DM030117" Type="DBDM0301" />
      <Association Name="DBDM0107_DBDM03011" Member="DBDM0301s1" ThisKey="DM010701" OtherKey="DM030117" Type="DBDM0301" />
      <Association Name="DBDM0107_DBDM0173" Member="DBDM0173s" ThisKey="DM010701" OtherKey="DM017310" Type="DBDM0173" />
      <Association Name="DBDM0107_DBDM0175" Member="DBDM0175s" ThisKey="DM010701" OtherKey="DM017510" Type="DBDM0175" />
    </Type>
  </Table>
  <Table Name="dbo.KyhieuVB" Member="KyhieuVBs">
    <Type Name="KyhieuVB">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Loaivanban" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Donvibanhanh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Kyhieuvanban" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0175" Member="DBDM0175s">
    <Type Name="DBDM0175">
      <Column Name="DM017501" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017502" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017503" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DM017504" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017505" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="DM017506" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DM017507" Type="System.String" DbType="NVarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="DM017508" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017509" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DM017510" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017511" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017512" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017513" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017514" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017515" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017516" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017517" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017518" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DM017519" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0175_DBDM0176" Member="DBDM0176s" ThisKey="DM017501" OtherKey="DM017602" Type="DBDM0176" />
      <Association Name="DBDM0107_DBDM0175" Member="DBDM0107" ThisKey="DM017510" OtherKey="DM010701" Type="DBDM0107" IsForeignKey="true" />
      <Association Name="DBDM0161_DBDM0175" Member="DBDM0161" ThisKey="DM017512" OtherKey="DM016101" Type="DBDM0161" IsForeignKey="true" />
      <Association Name="DBDM0202_DBDM0175" Member="DBDM0202" ThisKey="DM017504" OtherKey="DM020201" Type="DBDM0202" IsForeignKey="true" />
      <Association Name="DBDM0304_DBDM0175" Member="DBDM0304" ThisKey="DM017511" OtherKey="DM030401" Type="DBDM0304" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0176" Member="DBDM0176s">
    <Type Name="DBDM0176">
      <Column Name="DM017601" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017602" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017603" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017604" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DM017605" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0175_DBDM0176" Member="DBDM0175" ThisKey="DM017602" OtherKey="DM017501" Type="DBDM0175" IsForeignKey="true" />
      <Association Name="DBDM0165_DBDM0176" Member="DBDM0165" ThisKey="DM017603" OtherKey="DM016501" Type="DBDM0165" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDM0177" Member="DBDM0177s">
    <Type Name="DBDM0177">
      <Column Name="DM017701" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DM017702" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017703" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DM017704" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="DBDM0170_DBDM0177" Member="DBDM0170" ThisKey="DM017702" OtherKey="DM017001" Type="DBDM0170" IsForeignKey="true" />
    </Type>
  </Table>
</Database>